---@alias HeroClassType
---|`HERO_CLASS_NONE`
---|`HERO_CLASS_KNIGHT`
---|`HERO_CLASS_RANGER`
---|`HERO_CLASS_WIZARD`
---|`HERO_CLASS_DEMON_LORD`
---|`HERO_CLASS_NECROMANCER`
---|`HERO_CLASS_WARLOCK`
---|`HERO_CLASS_RUNEMAGE`
---|`HERO_CLASS_BARBARIAN`
HERO_CLASS_NONE = 0
HERO_CLASS_KNIGHT = 1
HERO_CLASS_RANGER = 2
HERO_CLASS_WIZARD = 3
HERO_CLASS_DEMON_LORD = 4
HERO_CLASS_NECROMANCER = 5
HERO_CLASS_WARLOCK = 6
HERO_CLASS_RUNEMAGE = 7
HERO_CLASS_BARBARIAN = 8

__end_import()