---@alias HeroSpecType
---|`HERO_SPEC_NONE`
---|`HERO_SPEC_SUZERAIN`
---|`HERO_SPEC_WHITE_KNIGHT`
---|`HERO_SPEC_JOUSTING`
---|`HERO_SPEC_PEASANTS`
---|`HERO_SPEC_ARCHERS`
---|`HERO_SPEC_FOOTMEN`
---|`HERO_SPEC_GRIFFINS`
---|`HERO_SPEC_WAR_MACHINES`
---|`HERO_SPEC_LOGISTICS`
---|`HERO_SPEC_HASTE`
---|`HERO_SPEC_FURIOUS`
---|`HERO_SPEC_GATE_KEEPER`
---|`HERO_SPEC_BEATER`
---|`HERO_SPEC_BOMBARDIER`
---|`HERO_SPEC_IMPREGNABLE`
---|`HERO_SPEC_HYPNOTIST`
---|`HERO_SPEC_FLAGBEARER_OF_DARKNESS`
---|`HERO_SPEC_HOUNDS`
---|`HERO_SPEC_SUCCUBUSES`
---|`HERO_SPEC_ELVEN_VOLLEY`
---|`HERO_SPEC_BLADE_MASTER`
---|`HERO_SPEC_ELVES`
---|`HERO_SPEC_UNICORNS`
---|`HERO_SPEC_ELVEN_FURY`
---|`HERO_SPEC_WAYLAYER`
---|`HERO_SPEC_CALL_OF_THE_WASP`
---|`HERO_SPEC_TALENTED_WARRIOR`
---|`HERO_SPEC_FOREST_GUARDIAN`
---|`HERO_SPEC_HEIR_OF_UNDEAD`
---|`HERO_SPEC_ZOMBIES`
---|`HERO_SPEC_VAMPIRES`
---|`HERO_SPEC_REANIMATOR`
---|`HERO_SPEC_MALEDICTOR`
---|`HERO_SPEC_DARK_EMISSARY`
---|`HERO_SPEC_MIND_CLEANER`
---|`HERO_SPEC_EMPIRIC`
---|`HERO_SPEC_SOULHUNTER`
---|`HERO_SPEC_MASTER_OF_ELEMENTS`
---|`HERO_SPEC_RADIANT`
---|`HERO_SPEC_INEXHAUSTIBLE`
---|`HERO_SPEC_FEATHER_MAGE`
---|`HERO_SPEC_DISRUPTER`
---|`HERO_SPEC_WEILDER_OF_FIRE`
---|`HERO_SPEC_GREMLINS`
---|`HERO_SPEC_GOLEMS`
---|`HERO_SPEC_MAGES`
---|`HERO_SPEC_PRUDENT`
---|`HERO_SPEC_EVASIVE`
---|`HERO_SPEC_POWER_BARGAIN`
---|`HERO_SPEC_RIDERS`
---|`HERO_SPEC_DARK_ACOLYTE`
---|`HERO_SPEC_POISONER`
---|`HERO_SPEC_MATRON_SALVO`
---|`HERO_SPEC_SAVAGE`
---|`HERO_SPEC_WITCHES`
---|`HERO_SPEC_MINOTAURS`
---|`HERO_SPEC_TIME_SHIFT`
---|`HERO_SPEC_BORDERGUARD`
---|`HERO_SPEC_COURTIER`
---|`HERO_SPEC_MOUNTAIN_KING`
---|`HERO_SPEC_AXE_MASTER`
---|`HERO_SPEC_BEAR_RIDERS`
---|`HERO_SPEC_MAGISTER`
---|`HERO_SPEC_RESEARCHER`
---|`HERO_SPEC_SACRED_HAMMER`
---|`HERO_SPEC_ECONOMIST`
---|`HERO_SPEC_DEFENDER`
---|`HERO_SPEC_STORMCALLER`
---|`HERO_SPEC_MASTER_OF_INITIATIVE`
---|`HERO_SPEC_CHOSEN_BY_GODS`
---|`HERO_SPEC_GRIM_FIGHTER`
---|`HERO_SPEC_RASH`
---|`HERO_SPEC_CENTAUR_MISTRESS`
---|`HERO_SPEC_OFFENDER`
---|`HERO_SPEC_WAR_LEADER`
---|`HERO_SPEC_WYVERN_TAMER`
---|`HERO_SPEC_BLOODDRINKER`
---|`HERO_SPEC_ORC_ELDER`
---|`HERO_SPEC_GOBLIN_KING`
---|`HERO_SPEC_DEMON_HUNTER`
---|`HERO_SPEC_AVATAR_OF_DEATH`
---|`HERO_SPEC_VESSEL_OF_ELRATH`
---|`HERO_SPEC_INFERNAL_MACHINE`
HERO_SPEC_NONE = 0
HERO_SPEC_SUZERAIN = 1
HERO_SPEC_WHITE_KNIGHT = 2
HERO_SPEC_JOUSTING = 3
HERO_SPEC_PEASANTS = 4
HERO_SPEC_ARCHERS = 5
HERO_SPEC_FOOTMEN = 6
HERO_SPEC_GRIFFINS = 7
HERO_SPEC_WAR_MACHINES = 8
HERO_SPEC_LOGISTICS = 9
HERO_SPEC_HASTE = 10
HERO_SPEC_FURIOUS = 11
HERO_SPEC_GATE_KEEPER = 12
HERO_SPEC_BEATER = 13
HERO_SPEC_BOMBARDIER = 14
HERO_SPEC_IMPREGNABLE = 15
HERO_SPEC_HYPNOTIST = 16
HERO_SPEC_FLAGBEARER_OF_DARKNESS = 17
HERO_SPEC_HOUNDS = 18
HERO_SPEC_SUCCUBUSES = 19
HERO_SPEC_ELVEN_VOLLEY = 20
HERO_SPEC_BLADE_MASTER = 21
HERO_SPEC_ELVES = 22
HERO_SPEC_UNICORNS = 23
HERO_SPEC_ELVEN_FURY = 24
HERO_SPEC_WAYLAYER = 25
HERO_SPEC_CALL_OF_THE_WASP = 26
HERO_SPEC_TALENTED_WARRIOR = 27
HERO_SPEC_FOREST_GUARDIAN = 28
HERO_SPEC_HEIR_OF_UNDEAD = 29
HERO_SPEC_ZOMBIES = 30
HERO_SPEC_VAMPIRES = 31
HERO_SPEC_REANIMATOR = 32
HERO_SPEC_MALEDICTOR = 33
HERO_SPEC_DARK_EMISSARY = 34
HERO_SPEC_MIND_CLEANER = 35
HERO_SPEC_EMPIRIC = 36
HERO_SPEC_SOULHUNTER = 37
HERO_SPEC_MASTER_OF_ELEMENTS = 38
HERO_SPEC_RADIANT = 39
HERO_SPEC_INEXHAUSTIBLE = 40
HERO_SPEC_FEATHER_MAGE = 41
HERO_SPEC_DISRUPTER = 42
HERO_SPEC_WEILDER_OF_FIRE = 43
HERO_SPEC_GREMLINS = 44
HERO_SPEC_GOLEMS = 45
HERO_SPEC_MAGES = 46
HERO_SPEC_PRUDENT = 47
HERO_SPEC_EVASIVE = 48
HERO_SPEC_POWER_BARGAIN = 49
HERO_SPEC_RIDERS = 50
HERO_SPEC_DARK_ACOLYTE = 51
HERO_SPEC_POISONER = 52
HERO_SPEC_MATRON_SALVO = 53
HERO_SPEC_SAVAGE = 54
HERO_SPEC_WITCHES = 55
HERO_SPEC_MINOTAURS = 56
HERO_SPEC_TIME_SHIFT = 57
HERO_SPEC_BORDERGUARD = 58
HERO_SPEC_COURTIER = 59
HERO_SPEC_MOUNTAIN_KING = 60
HERO_SPEC_AXE_MASTER = 61
HERO_SPEC_BEAR_RIDERS = 62
HERO_SPEC_MAGISTER = 63
HERO_SPEC_RESEARCHER = 64
HERO_SPEC_SACRED_HAMMER = 65
HERO_SPEC_ECONOMIST = 66
HERO_SPEC_DEFENDER = 67
HERO_SPEC_STORMCALLER = 68
HERO_SPEC_MASTER_OF_INITIATIVE = 69
HERO_SPEC_CHOSEN_BY_GODS = 70
HERO_SPEC_GRIM_FIGHTER = 71
HERO_SPEC_RASH = 72
HERO_SPEC_CENTAUR_MISTRESS = 73
HERO_SPEC_OFFENDER = 74
HERO_SPEC_WAR_LEADER = 75
HERO_SPEC_WYVERN_TAMER = 76
HERO_SPEC_BLOODDRINKER = 77
HERO_SPEC_ORC_ELDER = 78
HERO_SPEC_GOBLIN_KING = 79
HERO_SPEC_DEMON_HUNTER = 80
HERO_SPEC_AVATAR_OF_DEATH = 81
HERO_SPEC_VESSEL_OF_ELRATH = 82
HERO_SPEC_INFERNAL_MACHINE = 83

__end_import()